'use strict';
import {User} from "../../../entities/User";

export const SE_SURFACE_CRACK_STRAIGHT_PIPE = 'SE_SURFACE_CRACK_STRAIGHT_PIPE'
export const SIMPLE_IRON_BAR = 'SIMPLE_IRON_BAR'
export const SCENARIO_TYPES = [SE_SURFACE_CRACK_STRAIGHT_PIPE, SIMPLE_IRON_BAR];
export const USER = new User();


export const INTERNATIONAL = 'INT';
export const UNITEDSTATES = 'US';


//UNIDADES INTERNATIONAL
//DISTANCIA
export const CENTIMETER = 'CM';
export const MILLIMETER = 'MM';

//PRESION
export const KILOPASCAL = 'KPA';
export const MEGAPASCAL = 'MPA';

//FRACTURE_TOUGHNESS
export const MEGAPASCAL_METER_0_5 = 'MEGAPASCAL_METER_0_5';

export const INTERNATIONAL_UNITS = [CENTIMETER, MILLIMETER,KILOPASCAL,MEGAPASCAL,MEGAPASCAL_METER_0_5];


//UNIDADES US
//DISTANCIA
export const INCH = 'INCH';
export const FOOT = 'FOOT';
export const THOU = 'THOU';

//PRESION
export const KSI = 'KSI';
export const PSI = 'PSI';

//FRACTURE_TOUGHNESS
export const KSI_INCH_0_5 = 'KSI_INCH_0_5';



export const UNITEDSTATES_UNITS = [INCH, FOOT,THOU,KSI,PSI,KSI_INCH_0_5];


//MAGNITUDES
export const DISTANCE = 'DISTANCE';
export const PREASURE = 'PREASURE';
export const FRACTURE_TOUGHNESS = 'FRACTURE_TOUGHNESS';
export const PLASTIC_COLLAPSE = 'PLASTIC_COLLAPSE';

//TIPO DE PARAMETRO
export const DETERMINISTIC = 'DETERMINISTIC';
export const VARIABLE = 'VARIABLE';
export const NORMAL = 'NORMAL';
export const LOGNORMAL = 'LOGNORMAL';


export const  YIELD_STRESS = 'YIELD_STRESS';
export const MATERIAL_PROPERTIES = [FRACTURE_TOUGHNESS,PLASTIC_COLLAPSE,YIELD_STRESS];